### ISSUE TITLE
Pip not present

### ISSUE THREAD

**Issue by Norton-breman** [qualisys/qtm-scripting#19]
Hello,

I'm trying to install numpy but pip is not in QTM install directory next to python.exe. I also want to install tkinter since it is not in the distribution you provide. Are there any workaround ?

Otherwise, would it be possible to use an other python interpreter like the one I already have for my others projects ?

Thanks

**Comment by schoondw** [comment]
Hi,

QTM uses an embedded version of Python, it is not possible to use another interpreter.

Pip should be included by default. For using pip, please check out the instructions in the manual: https://docs.qualisys.com/qtm/index.html#Developer_appendix/scripting_external_packages.htm

Please note the limitations regarding the use of external packages due to the use of the embedded Python version. GUI functionality is not supported, so you probably cannot use the tkinter package for QTM scripting.

Best regards,
Erwin

**Comment by Norton-breman** [comment]
Hi,
thanks for your answer, I forgot to keep you informed but I already solved my problem. In fact, I'm pretty sure pip was not included in your embeded distribution. I had to install it using a script named get_pip that you can find here [https://github.com/pypa/get-pip](url).
Then, tkinter can't be install using pip but I finally used wxpython wich allowed me to add some gui to my qualisys/python devs.

Best regards,
Antoine

**Comment by schoondw** [comment]
Hi Antoine,
Good to hear that you solved the problem. I will check if pip is included with the latest version of QTM.
BR,
Erwin
