### ISSUE TITLE
Issues with counting of frames

### ISSUE THREAD

**Issue by ilya112358** [qualisys/qtm-scripting#5]
![image](https://github.com/qualisys/qtm-scripting/assets/9436418/8948acf9-5455-452f-9c05-c3ce99b13a95)
I blame the guy who invented zero-based array indexing ) The number of errors introduced over the years due to that convention is uncountable.

There is another issue here though. The total number of frames is one frame short to display the whole record. Like, in my example, we need 801 frames to show all frames from 0.00s to 8.00s. We have only 800 which means we can never see the very last frame.
![image](https://github.com/qualisys/qtm-scripting/assets/9436418/a80f414f-fc1c-46f9-b8a2-dc2eb797fcbe)

**Comment by schoondw** [comment]
Hi Ilya,
Thanks for your comments. The indexing in the scripting API is indeed zero based, whereas in QTM the frames start at 1. In the scripting you will need to take this into account. 
The number of frames is correct though. In your example there are 800 frames in the recording. In QTM the frames run from 1-800, in the scripting it runs from 0-799, giving access to the full frame range. It may be misleading that QTM indicates the time as 7.99 of 8.00 s, even if t = 8.00 actually does not exist in the recording, but this is due to rounding.
Hope this answers your question.
/Erwin

**Comment by demilsson** [comment]
Regarding the "7.99s of 8.00s" issue, I might add that it probably isn't a rounding issue either. Each frame represents a unit of time. The sum of all the frames (units of time) is the total length of the recording.

The time indicator in QTM indicates the starting time of the current frame. If the indicator is at the very beginning, the start of the first frame is `0s`. If the indicator is at the very end, the start of the last frame is the `total duration` _minus_ `the length of the last frame`.

It might be easier to conceptualise if you consider a recording of `10` frames at `1s` each - making a duration of `10s`. At `0s`, the first frame has just become active. At `10s` the last frame has just ended. The last frame starts at `9s`, and this is what would be indicated in QTM when the indicator is pointing to the last frame.

**Comment by ilya112358** [comment]
I see, that makes sense. It is often murky at the endpoints of intervals. And I guess, the story of "the first is the zeroth... but not always" will continue into the ages to come, so I'll close the issue.

MC & HNY!
